job:
  url: 'https://zensus-pl.corp.capgemini.com/gitlab/TestTools/ZENSUSTEMPLATE_JMETER.git'
  jobName: 'example'
  description: 'Description of the job'
  type: 'selenium'
  environment: 'dev1'
  browser: safari