job:
  description: 'Generic Job Description'
  scriptPath: 'Jenkinsfile'
  credentialsId: ''
  enabled: true
  type: 'selenium'
  environment: 'dev1'
  regression:
    branches:
      includes: '*develop'
      excludes: 'boo'
    enabled: true
    trigger: 'periodic(66)'
  feature:
    branches:
      includes: '*'
      excludes: 'master'
    enabled: true
    trigger: 'periodic(66)'
  standalone:
    branches:
      includes: 'master'
    enabled: true
  orphanedOldItemsNumKeep: 6
  orphanedOldItemsDaysKeep: 6
  oldItemsNumKeep: 6
  oldItemsDaysKeep: 6
  oldArtifactsNumKeep: 6
  oldArtifactsDaysKeep: 6
  browser: firefox